spring:
  application:
    name: invest-visor

  # ============== r2dbc ==============
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/invest-db
    username: invest-db
    password: invest-db

server:
  port: 9981

# ============== gRPC ==============
analytics:
  server:
    python:
      port: 9999
    golang:
      port: 8888
  provider:
    methods:
      getMathExpectation: python
      getLine: python

# ============== T-Invest API ==============
tinvest:
  sandbox:
    host: sandbox-invest-public-api.tinkoff.ru:443
    token:
