# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_server/proto/analytics_api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_server/proto/analytics_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%grpc_server/proto/analytics_api.proto\x12\x15ru.shilaev.invest_bot\"\x1e\n\x0bNumberArray\x12\x0f\n\x07numbers\x18\x01 \x03(\x01\"!\n\x0f\x41nalyticsResult\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32n\n\x0e\x44\x61taProcessing\x12\\\n\x0eProcessNumbers\x12\".ru.shilaev.invest_bot.NumberArray\x1a&.ru.shilaev.invest_bot.AnalyticsResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server.proto.analytics_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERARRAY']._serialized_start=64
  _globals['_NUMBERARRAY']._serialized_end=94
  _globals['_ANALYTICSRESULT']._serialized_start=96
  _globals['_ANALYTICSRESULT']._serialized_end=129
  _globals['_DATAPROCESSING']._serialized_start=131
  _globals['_DATAPROCESSING']._serialized_end=241
# @@protoc_insertion_point(module_scope)
