# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import analytics_api_pb2 as analytics__api__pb2


class DataProcessingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessNumbers = channel.unary_unary(
                '/ru.shilaev.investvisor.DataProcessing/ProcessNumbers',
                request_serializer=analytics__api__pb2.NumberArray.SerializeToString,
                response_deserializer=analytics__api__pb2.AnalyticsResult.FromString,
                )


class DataProcessingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessNumbers,
                    request_deserializer=analytics__api__pb2.NumberArray.FromString,
                    response_serializer=analytics__api__pb2.AnalyticsResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ru.shilaev.investvisor.DataProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataProcessing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ru.shilaev.investvisor.DataProcessing/ProcessNumbers',
            analytics__api__pb2.NumberArray.SerializeToString,
            analytics__api__pb2.AnalyticsResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
