# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics_api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61nalytics_api.proto\x12\x16ru.shilaev.investvisor\"\x1e\n\x0bNumberArray\x12\x0f\n\x07numbers\x18\x01 \x03(\x01\"!\n\x0f\x41nalyticsResult\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32p\n\x0e\x44\x61taProcessing\x12^\n\x0eProcessNumbers\x12#.ru.shilaev.investvisor.NumberArray\x1a\'.ru.shilaev.investvisor.AnalyticsResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NUMBERARRAY']._serialized_start=47
  _globals['_NUMBERARRAY']._serialized_end=77
  _globals['_ANALYTICSRESULT']._serialized_start=79
  _globals['_ANALYTICSRESULT']._serialized_end=112
  _globals['_DATAPROCESSING']._serialized_start=114
  _globals['_DATAPROCESSING']._serialized_end=226
# @@protoc_insertion_point(module_scope)
